post_install() {
    echo -e "NOTE:"
    echo -e "\tThe newsup.conf file was installed in /etc/newsup/"
    echo -e "\tIn order for newsup to find it, you need to copy it to 
~/.config/"
    echo -e "\tMake your changes on ~/.config/newsup.conf"
    echo -e ""
    echo -e "NOTE 2:"
    echo -e "\tThis package build doesn't install the IRC bot."
    echo -e "\tIf you want it, you'll need to install it manually, or 
adapt this PKGBUILD"
}
